//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailInfo
    {
        public int ID { get; set; }
        public string BillsInfo { get; set; }
        public string CodeInfo { get; set; }
        public string GoodsName { get; set; }
        public string GoodsSort { get; set; }
        public string UnitInfo { get; set; }
        public Nullable<double> GoodsNum { get; set; }
        public Nullable<double> PayPrice { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string BackupInfo { get; set; }
    }
}
