//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsInfo
    {
        public int ID { get; set; }
        public string CodeInfo { get; set; }
        public string GoodsName { get; set; }
        public string GoodsType { get; set; }
        public string GoodsSort { get; set; }
        public string GoodsUnit { get; set; }
        public Nullable<double> PurPrice { get; set; }
        public Nullable<double> PayPrice { get; set; }
        public string BackupInfo { get; set; }
        public string SupInfo { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string AddPerson { get; set; }
        public Nullable<int> SortInfoId { get; set; }
        public string Profit { get; set; }
    }
}
