//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smarketEntities : DbContext
    {
        public smarketEntities()
            : base("name=smarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetailInfo> DetailInfo { get; set; }
        public virtual DbSet<GoodsInfo> GoodsInfo { get; set; }
        public virtual DbSet<SalesInfo> SalesInfo { get; set; }
        public virtual DbSet<SortInfo> SortInfo { get; set; }
        public virtual DbSet<StockClassInfo> StockClassInfo { get; set; }
        public virtual DbSet<StockInfo> StockInfo { get; set; }
        public virtual DbSet<SuppliersInfo> SuppliersInfo { get; set; }
        public virtual DbSet<UnitInfo> UnitInfo { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
    }
}
