//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockInfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> GoodId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Batch { get; set; }
        public Nullable<decimal> JPrice { get; set; }
        public Nullable<int> SupId { get; set; }
    }
}
