//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersInfo
    {
        public int ID { get; set; }
        public string SupName { get; set; }
        public string TeleInfo { get; set; }
        public string AddressInfo { get; set; }
        public string ZipInfo { get; set; }
        public string PersonInfo { get; set; }
        public string BackupInfo { get; set; }
        public string PhoneInfo { get; set; }
    }
}
