//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int ID { get; set; }
        public string UserAccount { get; set; }
        public string PassWordInfo { get; set; }
        public string UserName { get; set; }
        public string UserTele { get; set; }
        public string BackupInfo { get; set; }
        public string PayInfo { get; set; }
    }
}
